language: ruby
rvm:
  - "2.3.0"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec #&& ember test

before_install:
  - sudo apt-get install -y postgresql-server-dev-all
#  - sudo apt-get install phantomjs

install:
  - bundle install
  
services:
  - redis-server
  
env:
  - REDIS_URL=redis://localhost:6379/